---
- hosts: all
  gather_facts: false
  tasks:
    - name: Connection/Defaut User Details
      win_whoami:
    - name: Become User Details
      win_whoami:
      become: yes
      become_method: runas
      become_user: Administrator
  vars:
    ansible_become_pass: Password01
